FROM mono:latest

ENV DOCFX_VER 2.58

# RUN apt-get update \
#  && apt-get install gnupg ca-certificates -y \
#  && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
# && echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list
#  && apt-get update \
#  && apt install mono-devel -y

# DOCFX Releases
# https://github.com/dotnet/docfx/releases
# https://github.com/dotnet/docfx/releases/download/v2.58/docfx.zip


RUN apt-get update \
 && apt-get install unzip wget nginx git -y \
 && rm -rf /var/lib/apt/lists/* \
 && wget -q -P /tmp https://github.com/dotnet/docfx/releases/download/v${DOCFX_VER}/docfx.zip \
 && mkdir -p /opt/docfx \
 && unzip /tmp/docfx.zip -d /opt/docfx \
 && echo '#!/bin/bash\nmono /opt/docfx/docfx.exe $@' > /usr/bin/docfx \
 && chmod +x /usr/bin/docfx \
 && rm -f /tmp/*

# Create source directory
RUN mkdir -p /source

COPY .bashrc /root/.bashrc
COPY .bash_aliases /root/aliases

# Configure the tools and scripts
# COPY entrypoint.sh /
# RUN chmod 755 /entrypoint.sh
# COPY nginx.conf /etc/nginx/nginx.conf

# Set working directory
WORKDIR /source

# Expose port 80
EXPOSE 80

# ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/bin/bash" ] 
