from alpine

RUN apk --update add nodejs

# Create work directory
WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install

COPY ./app.js ./app.js

EXPOSE 50000 

RUN apk --update add curl
HEALTHCHECK CMD curl -4 --fail -s localhost:50000/ || exit 1

CMD [ "npm", "start"]
