FROM arm64v8/ubuntu:22.04

# DOCFX Releases
# https://github.com/dotnet/docfx/releases


RUN apt-get update \
 && apt-get install unzip wget nginx git libunwind8 dotnet-sdk-7.0 -y

# Add dotnet tools to path.
ENV PATH="${PATH}:/root/.dotnet/tools"

# Install DocFX as a dotnet tool.
RUN dotnet tool update -g docfx && \
    docfx --version

# Create source directory
RUN mkdir -p /source

# Configure the tools and scripts
COPY entrypoint.sh /
RUN chmod 755 /entrypoint.sh
COPY nginx.conf /etc/nginx/nginx.conf

# Set working directory
WORKDIR /source

# Expose port 80
EXPOSE 80

ENTRYPOINT [ "/entrypoint.sh" ]
# CMD [ "/bin/bash" ] 
